---
# Configuration for Alacritty, the GPU enhanced terminal emulator
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command.
  TERM: xterm-256color
  COLORTERM: truecolor

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /bin/zsh
  args:
    - --login

window:
  startup_mode: Maximized
  dynamic_title: false

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

mouse:
  hide_when_typing: true

# Font configuration (changes require restart).
font:
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Nerd Font Mono
    style: Medium

  bold:
    family: Iosevka Nerd Font Mono
    style: Bold

  italic:
    family: Iosevka Nerd Font Mono
    style: Medium

  # Point size of the font.
  size: 11
  # Offset is the extra space around each character. offset.y can be thought
  # of as modifying the linespacing, and offset.x as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0

# Colors.
# Palette is taken from https://github.com/projekt0n/github-nvim-theme.
schemes:
  github_dark: &dark # Default colors
    primary:
      background: "#24292e"
      foreground: "#d1d5da"

    # Normal colors
    normal:
      black: "#a8b7c8"
      red: "#ea4a5a"
      green: "#34d058"
      yellow: "#ffea7f"
      blue: "#2188ff"
      magenta: "#b392f0"
      cyan: "#39c5cf"
      white: "#2c313a"

    # Bright colors
    bright:
      black: "#959da5"
      red: "#f97583"
      green: "#85e89d"
      yellow: "#ffea7f"
      blue: "#79b8ff"
      magenta: "#b392f0"
      cyan: "#56d4dd"
      white: "#000000"

    indexed_colors:
      - { index: 16, color: "#d18616" }
      - { index: 17, color: "#f97583" }

  github_light: &light # Default colors
    primary:
      background: "#ffffff"
      foreground: "#24292f"

    # Normal colors
    normal:
      black: "#677684"
      red: "#d73a49"
      green: "#28a745"
      yellow: "#dbab09"
      blue: "#0366d6"
      magenta: "#5a32a3"
      cyan: "#0598bc"
      white: "#d5e5f6"

    # Bright colors
    bright:
      black: "#959da5"
      red: "#cb2431"
      green: "#22863a"
      yellow: "#b08800"
      blue: "#005cc5"
      magenta: "#5a32a3"
      cyan: "#3192aa"
      white: "#4c535a"

    indexed_colors:
      - { index: 16, color: "#d18616" }
      - { index: 17, color: "#cb2431" }

# Colors
colors: *light
