---
# Configuration for Alacritty, the GPU enhanced terminal emulator
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command.
  TERM: xterm-256color
  COLORTERM: truecolor

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /bin/zsh
  args:
    - --login

window:
  startup_mode: Maximized
  dynamic_title: false

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

mouse:
  hide_when_typing: true

# Font configuration (changes require restart).
font:
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Nerd Font Mono
    style: Medium

  bold:
    family: Iosevka Nerd Font Mono
    style: Bold

  italic:
    family: Iosevka Nerd Font Mono
    style: Medium

  # Point size of the font.
  size: 11
  # Offset is the extra space around each character. offset.y can be thought
  # of as modifying the linespacing, and offset.x as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0

# Colors.
# Palette is taken from https://github.com/folke/tokyonight.nvim/blob/main/extras/alacritty.
schemes:
  tokyonight_night: &dark
    # Default colors
    # Default colors
    primary:
      background: "#1a1b26"
      foreground: "#c0caf5"

    # Normal colors
    normal:
      black: "#15161e"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#a9b1d6"

    # Bright colors
    bright:
      black: "#414868"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#c0caf5"

    indexed_colors:
      - { index: 16, color: "#ff9e64" }
      - { index: 17, color: "#db4b4b" }

  tokyonight_day: &light
    # Default colors
    # Default colors
    primary:
      background: "#e1e2e7"
      foreground: "#3760bf"

    # Normal colors
    normal:
      black: "#e9e9ed"
      red: "#f52a65"
      green: "#587539"
      yellow: "#8c6c3e"
      blue: "#2e7de9"
      magenta: "#9854f1"
      cyan: "#007197"
      white: "#6172b0"

    # Bright colors
    bright:
      black: "#a1a6c5"
      red: "#f52a65"
      green: "#587539"
      yellow: "#8c6c3e"
      blue: "#2e7de9"
      magenta: "#9854f1"
      cyan: "#007197"
      white: "#3760bf"

  indexed_colors:
    - { index: 16, color: "#b15c00" }
    - { index: 17, color: "#c64343" }

# Colors
colors: *dark
