---
# Configuration for Alacritty, the GPU enhanced terminal emulator
# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command.
  COLORTERM: truecolor
  TERM: xterm-256color

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
# shell:
#   program: /bin/zsh
#   args:
#     - --login

window:
  startup_mode: Maximized
  dynamic_title: false
  decorations: None

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

mouse:
  hide_when_typing: true

key_bindings:
  - { key: Period, mods: Control, chars: "\e[46;5u" } # Ctrl-. on Emacs
  - { key: Comma, mods: Control, chars: "\e[44;5u" } # Ctrl-, on Emacs

# Font configuration (changes require restart).
font:
  # The normal (roman) font face to use.
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Semibold

  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Semibold Italic

  bold:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraBold

  bold-italic:
    family: JetBrainsMono Nerd Font Mono
    style: ExtraBold Italic

  # Point size of the font.
  size: 10.5
  # Offset is the extra space around each character. offset.y can be thought
  # of as modifying the linespacing, and offset.x as modifying the letter
  # spacing.
  offset:
    x: 0
    y: 0

colors:
  primary:
    background: "${TTY_COLOR_BG0}"
    foreground: "${TTY_COLOR_FG0}"

  # Normal colors
  normal:
    black: "${TTY_COLOR_BLACK}"
    red: "${TTY_COLOR_RED}"
    green: "${TTY_COLOR_GREEN}"
    yellow: "${TTY_COLOR_YELLOW}"
    blue: "${TTY_COLOR_BLUE}"
    magenta: "${TTY_COLOR_MAGENTA}"
    cyan: "${TTY_COLOR_CYAN}"
    white: "${TTY_COLOR_WHITE}"

  # Bright colors
  bright:
    black: "${TTY_COLOR_BRIGHT_BLACK}"
    red: "${TTY_COLOR_BRIGHT_RED}"
    green: "${TTY_COLOR_BRIGHT_GREEN}"
    yellow: "${TTY_COLOR_BRIGHT_YELLOW}"
    blue: "${TTY_COLOR_BRIGHT_BLUE}"
    magenta: "${TTY_COLOR_BRIGHT_MAGENTA}"
    cyan: "${TTY_COLOR_BRIGHT_CYAN}"
    white: "${TTY_COLOR_BRIGHT_WHITE}"
