---
# Configuration for Alacritty, the GPU enhanced terminal emulator


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command.
  TERM: xterm-256color
  COLORTERM: truecolor

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /bin/zsh
  args:
    - --login

window:
  startup_mode: Maximized

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart).
font:
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Term
    style: Medium

  bold:
    family: Iosevka Term
    style: Bold

  italic:
    family: Iosevka Term
    style: Italic

  # Point size of the font.
  size: 11
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

schemes:
  # Kanagawa Alacritty Colors
  kanagawa_dark: &dark

    primary:
      background: '0x1f1f28'
      foreground: '0xdcd7ba'

    normal:
      black:   '0x090618'
      red:     '0xc34043'
      green:   '0x76946a'
      yellow:  '0xc0a36e'
      blue:    '0x7e9cd8'
      magenta: '0x957fb8'
      cyan:    '0x6a9589'
      white:   '0xc8c093'

    bright:
      black:   '0x727169'
      red:     '0xe82424'
      green:   '0x98bb6c'
      yellow:  '0xe6c384'
      blue:    '0x7fb4ca'
      magenta: '0x938aa9'
      cyan:    '0x7aa89f'
      white:   '0xdcd7ba'

    selection:
      background: '0x2d4f67'
      foreground: '0xc8c093'

    indexed_colors:
      - { index: 16, color: '0xffa066' }
      - { index: 17, color: '0xff5d62' }

  one_light: &light
    # Github Light Colors.
    # See https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox/palette.lua
    primary:
      background: '#fbf1c7'
      foreground: '#282828'

    # Normal colors
    normal:
      black:   '#fbf1c7'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#7c6f64'

    # Bright colors
    bright:
      black:   '#928374'
      red:     '#9d0006'
      green:   '#79740e'
      yellow:  '#b57614'
      blue:    '#076678'
      magenta: '#8f3f71'
      cyan:    '#427b58'
      white:   '#3c3836'

# Colors
colors: *dark
