---
# Configuration for Alacritty, the GPU enhanced terminal emulator


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization. Default is xterm-256color
  # Note: the default TERM value `xterm-256color` does not
  # specify all features alacritty supports. This does pose
  # a few issues with programs relying on terminfo and the
  # `tput` command.
  TERM: xterm-256color
  COLORTERM: truecolor

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /bin/zsh
  args:
    - --login

window:
  startup_mode: Maximized

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart).
font:
  # The normal (roman) font face to use.
  normal:
    family: Iosevka Term
    style: Medium

  bold:
    family: Iosevka Term
    style: Bold

  italic:
    family: Iosevka Term
    style: Italic

  # Point size of the font.
  size: 11
  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0
    y: 0

# Modus themes.
# Colors.
schemes:
  dark: &dark
    primary:
      background: '#000000'
      foreground: '#FFFFFF'

    normal:
      black: '#000000'
      red: '#FF8059'
      green: '#44BC44'
      yellow: '#D0BC00'
      blue: '#2FAFFF'
      magenta: '#FEACD0'
      cyan: '#00D3D0'
      white: '#FFFFFF'

    bright:
      black: '#A8A8A8'
      red: '#FFA7BA'
      green: '#70D73F'
      yellow: '#DBBE5F'
      blue: '#34CFFF'
      magenta: '#D5B1FF'
      cyan: '#00D8B4'
      white: '#F4F4F4'

  light: &light
    primary:
      background: '#FFFFFF'
      foreground: '#000000'

    # Normal colors
    normal:
      black: '#FFFFFF'
      red: '#A60000'
      green: '#005E00'
      yellow: '#813E00'
      blue: '#0031A9'
      magenta: '#721045'
      cyan: '#00538B'
      white: '#000000'

    # Bright colors
    bright:
      black: '#505050'
      red: '#8A0000'
      green: '#006800'
      yellow: '#702F00'
      blue: '#0030B4'
      magenta: '#5C2092'
      cyan: '#003F8A'
      white: '#0A0A0A'

# Colors
colors: *dark
